name: Deploy Nuxt App to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Enable Corepack and Install Correct Yarn Version
      run: |
        corepack enable
        corepack prepare yarn@4.5.1 --activate

    - name: Install Dependencies
      run: yarn install

    - name: Debug SCSS Files
      run: ls -la ./assets/sass

    - name: Build Nuxt.js Project
      run: yarn build || echo "Build failed!"

    - name: Debug Nuxt.js Logs
      run: |
        echo "Nuxt build logs:"
        cat .nuxt/build.log || echo "No build log found"

    - name: Check Build Directory
      run: ls -la ./dist || echo "No dist directory found!"

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
      run: |
        npm install -g aws-cli
        aws s3 sync ./dist s3://my-nuxt-app --delete
